apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: patch-discovery-server-image
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: [v1]
        operations: [CREATE, UPDATE]
        resources: [pods]
        scope: Namespaced
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |-
          [
            JSONPatch{
              op: "replace",
              path: "/spec/containers/0/image",
              value: "europe-docker.pkg.dev/gardener-project/public/gardener/gardener-discovery-server:latest"
            }
          ]
