# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

{{- if (and .Values.workloadIdentity.openIDConfig .Values.workloadIdentity.jwks) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-workload-identity
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  openid-configuration.json: {{ required ".Values.workloadIdentity.openIDConfig is required" .Values.workloadIdentity.openIDConfig | b64enc }}
  jwks.json: {{ required ".Values.workloadIdentity.jwks is required" .Values.workloadIdentity.jwks | b64enc }}
{{- end }}
